cars = [
  {
    "id": "tesla-model-y",
    "name": "Model Y",
    "brand": "Tesla",
    "type": "Electric",
    "numericPrice": 6800000,
    "price": "₹68,00,000",
    "engine_battery": "Dual Motor AWD (75 kWh)",
    "horsepower": 384,
    "efficiency_range": "533 km range",
    "acceleration": "4.8s (0-100 km/h)",
    "topSpeed": "217 km/h",
    "pros": ["Spacious interior", "Leading charging network", "Excellent autopilot features"],
    "cons": ["Stiff ride quality", "No physical buttons", "Build quality inconsistency"],
    "image_url": "https://images.unsplash.com/photo-1619767886558-efdc259cde1a?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "hyundai-ioniq-5",
    "name": "Ioniq 5",
    "brand": "Hyundai",
    "type": "Electric",
    "numericPrice": 4600000,
    "price": "₹46,00,000",
    "engine_battery": "72.6 kWh Battery",
    "horsepower": 305,
    "efficiency_range": "631 km range",
    "acceleration": "5.2s (0-100 km/h)",
    "topSpeed": "185 km/h",
    "pros": ["Stunning retro-futuristic design", "Ultra-fast 800V charging", "Spacious and comfortable cabin"],
    "cons": ["Rear visibility is limited", "Small front trunk", "Basic lane keeping can be intrusive"],
    "image_url": "https://images.unsplash.com/photo-1669012591605-e1d900b73df7?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "bmw-x5",
    "name": "X5",
    "brand": "BMW",
    "type": "SUV",
    "numericPrice": 9500000,
    "price": "₹95,00,000",
    "engine_battery": "3.0L TwinPower Turbo I6",
    "horsepower": 375,
    "efficiency_range": "12 km/l mileage",
    "acceleration": "5.4s (0-100 km/h)",
    "topSpeed": "243 km/h",
    "pros": ["Powerful engine options", "Ultra-luxurious interior", "Engaging driving dynamics"],
    "cons": ["Cramped third-row option", "Expensive options packages", "Complicated infotainment layout"],
    "image_url": "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "audi-a6",
    "name": "A6",
    "brand": "Audi",
    "type": "Luxury",
    "numericPrice": 6200000,
    "price": "₹62,00,000",
    "engine_battery": "2.0L TFSI Turbo I4",
    "horsepower": 244,
    "efficiency_range": "14 km/l mileage",
    "acceleration": "6.8s (0-100 km/h)",
    "topSpeed": "250 km/h",
    "pros": ["Extremely quiet cabin", "High-tech dual touchscreen UI", "Superb ride comfort"],
    "cons": ["Understated design looks dated", "Numb steering feedback", "Trunk space is average"],
    "image_url": "https://images.unsplash.com/photo-1606152421802-db97b9c7a11b?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "porsche-911",
    "name": "911 Carrera",
    "brand": "Porsche",
    "type": "Sports",
    "numericPrice": 18600000,
    "price": "₹1,86,00,000",
    "engine_battery": "3.0L Twin-Turbo Flat-6",
    "horsepower": 379,
    "efficiency_range": "9 km/l mileage",
    "acceleration": "4.0s (0-100 km/h)",
    "topSpeed": "293 km/h",
    "pros": ["Flawless handling and steering", "Everyday supercar comfort", "Iconic styling and legacy"],
    "cons": ["Virtually useless rear seats", "Astronomical options pricing", "Minimal cabin storage space"],
    "image_url": "https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "ford-mustang",
    "name": "Mustang GT",
    "brand": "Ford",
    "type": "Sports",
    "numericPrice": 7500000,
    "price": "₹75,00,000",
    "engine_battery": "5.0L Coyote V8",
    "horsepower": 480,
    "efficiency_range": "8 km/l mileage",
    "acceleration": "4.2s (0-100 km/h)",
    "topSpeed": "250 km/h",
    "pros": ["Glorious V8 exhaust rumble", "Aggressive muscle styling", "Great value-to-performance"],
    "cons": ["Heavy steering in tight corners", "Subpar fuel economy", "Cheap interior plastics in lower trims"],
    "image_url": "https://images.unsplash.com/photo-1611245801755-734be013c7a2?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "toyota-camry",
    "name": "Camry Hybrid",
    "brand": "Toyota",
    "type": "Sedan",
    "numericPrice": 4800000,
    "price": "₹48,00,000",
    "engine_battery": "2.5L 4-Cylinder Hybrid",
    "horsepower": 218,
    "efficiency_range": "23 km/l mileage",
    "acceleration": "8.0s (0-100 km/h)",
    "topSpeed": "180 km/h",
    "pros": ["Unbeatable fuel efficiency", "Legendary reliability", "Extremely smooth ride"],
    "cons": ["Boring driving dynamics", "Outdated infotainment graphics", "Loud CVT engine drone under heavy acceleration"],
    "image_url": "https://images.unsplash.com/photo-1621007947382-cc34a6256c64?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "honda-civic",
    "name": "Civic",
    "brand": "Honda",
    "type": "Sedan",
    "numericPrice": 2500000,
    "price": "₹25,00,000",
    "engine_battery": "1.5L Turbocharged I4",
    "horsepower": 178,
    "efficiency_range": "16 km/l mileage",
    "acceleration": "7.5s (0-100 km/h)",
    "topSpeed": "200 km/h",
    "pros": ["Upscale cabin design", "Agile and fun handling", "Excellent resale value"],
    "cons": ["Noisy at highway speeds", "No physical volume knob on passenger side", "Low driving position might annoy some"],
    "image_url": "https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "mercedes-gle",
    "name": "GLE 450",
    "brand": "Mercedes-Benz",
    "type": "SUV",
    "numericPrice": 9900000,
    "price": "₹99,00,000",
    "engine_battery": "3.0L Turbo I6 with Mild Hybrid",
    "horsepower": 375,
    "efficiency_range": "10 km/l mileage",
    "acceleration": "5.6s (0-100 km/h)",
    "topSpeed": "250 km/h",
    "pros": ["State-of-the-art MBUX screen", "Unmatched suspension luxury", "Extremely quiet drive"],
    "cons": ["Very expensive upkeep", "Touch controls can be frustrating", "Third-row space is tight"],
    "image_url": "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "jeep-wrangler",
    "name": "Wrangler Rubicon",
    "brand": "Jeep",
    "type": "SUV",
    "numericPrice": 6500000,
    "price": "₹65,00,000",
    "engine_battery": "2.0L Turbocharged I4",
    "horsepower": 270,
    "efficiency_range": "9 km/l mileage",
    "acceleration": "7.6s (0-100 km/h)",
    "topSpeed": "177 km/h",
    "pros": ["Unmatched off-road capability", "Removable doors and roof", "Rugged, classic look"],
    "cons": ["Noisy on the highway", "Rough and bumpy ride", "Poor fuel economy"],
    "image_url": "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "toyota-rav4",
    "name": "RAV4",
    "brand": "Toyota",
    "type": "SUV",
    "numericPrice": 3500000,
    "price": "₹35,00,000",
    "engine_battery": "2.5L 4-Cylinder",
    "horsepower": 203,
    "efficiency_range": "14 km/l mileage",
    "acceleration": "8.2s (0-100 km/h)",
    "topSpeed": "190 km/h",
    "pros": ["Generous cargo capacity", "User-friendly dashboard", "Standard driver safety aids"],
    "cons": ["Engine sounds coarse when pushed", "Basic passenger seat adjustment", "Uninspired styling"],
    "image_url": "https://images.unsplash.com/photo-1606225457115-9b0de873c5db?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "porsche-taycan",
    "name": "Taycan",
    "brand": "Porsche",
    "type": "Electric",
    "numericPrice": 16000000,
    "price": "₹1,60,00,000",
    "engine_battery": "79.2 kWh Battery",
    "horsepower": 402,
    "efficiency_range": "484 km range",
    "acceleration": "5.4s (0-100 km/h)",
    "topSpeed": "230 km/h",
    "pros": ["Incredible Porsche driving feel", "Futuristic multi-screen interior", "Blazing-fast charging rates"],
    "cons": ["Cramped rear seats", "Real-world range is average", "Extremely high base price"],
    "image_url": "https://images.unsplash.com/photo-1611245801217-062e74de0555?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "lexus-es",
    "name": "ES 300h",
    "brand": "Lexus",
    "type": "Luxury",
    "numericPrice": 6300000,
    "price": "₹63,00,000",
    "engine_battery": "2.5L Hybrid Setup",
    "horsepower": 215,
    "efficiency_range": "22 km/l mileage",
    "acceleration": "8.9s (0-100 km/h)",
    "topSpeed": "180 km/h",
    "pros": ["Silky smooth ride quality", "Whisper-quiet cruising cabin", "Bulletproof reliability stats"],
    "cons": ["Suggish acceleration response", "Infotainment trackpad is finicky", "Rear seatbacks do not fold"],
    "image_url": "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "ford-f150",
    "name": "F-150 Lightning",
    "brand": "Ford",
    "type": "Truck",
    "numericPrice": 8500000,
    "price": "₹85,00,000",
    "engine_battery": "Standard Range (98 kWh)",
    "horsepower": 452,
    "efficiency_range": "386 km range",
    "acceleration": "4.1s (0-100 km/h)",
    "topSpeed": "180 km/h",
    "pros": ["Massive front trunk (Frunk)", "Power outlets feed appliances", "Tows heavy loads easily"],
    "cons": ["Towing cuts range in half", "Enormous dimensions make parking hard", "Long charging times on Level 2"],
    "image_url": "https://images.unsplash.com/photo-1583121274602-3e2820c69888?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "rivian-r1t",
    "name": "R1T Adventure",
    "brand": "Rivian",
    "type": "Truck",
    "numericPrice": 9200000,
    "price": "₹92,00,000",
    "engine_battery": "Large Pack (135 kWh) Quad-Motor",
    "horsepower": 835,
    "efficiency_range": "528 km range",
    "acceleration": "3.0s (0-100 km/h)",
    "topSpeed": "180 km/h",
    "pros": ["Sports-car acceleration times", "Unrivaled gear tunnel storage", "Incredible off-road mode adjustments"],
    "cons": ["No Apple CarPlay / Android Auto", "Wind noise from boxy side mirrors", "Expensive to repair body panels"],
    "image_url": "https://images.unsplash.com/photo-1669076214553-6ef72e0a294b?auto=format&fit=crop&w=600&q=80"
  }
]
